language: java
jdk:
- oraclejdk8
git:
  submodules: false
notifications:
  email: false
  slack:
    rooms: dejavu-psk:yYAY30VYZ6Pb2bfuSEYywGpZ#builds
    on_success: never
    on_failure: always
install:
- mvn clean install -B
script:
- mvn test -B
addons:
  ssh_known_hosts: 159.89.106.85
before_install:
- openssl aes-256-cbc -K $encrypted_a37725e5c31f_key -iv $encrypted_a37725e5c31f_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x .travis/push.s && .travis/push.sh
  on:
    branch: master