CREATE OR REPLACE VIEW productsWithDiscount AS (
  SELECT
    P.ID AS PRODUCT_ID,
    P.PRICE AS PRODUCT_PRICE,
    IFNULL( MAX( ABSOLUTE_DISCOUNT.VALUE), 0) AS P_ABSOLUTE,
    bcd.ABSOLUTE_DISCOUNT C_ABSOLUTE,
    e.ABSOLUTE AS E_ABSOLUTE,
    IFNULL( MAX( PERCNTAGE_DISCOUNT.VALUE), 0) AS P_PERCENTAGE,
    bcd.PERCENTAGE_DISCOUNT AS C_PERCENTAGE,
    e.PERCENTAGE AS E_PERCENTAGE
  FROM product P
    LEFT JOIN productDiscount PD on P.ID = PD.PRODUCTID
    LEFT JOIN discount ABSOLUTE_DISCOUNT on PD.ID = ABSOLUTE_DISCOUNT.ID AND ABSOLUTE_DISCOUNT.TYPE = 'ABSOLUTE'
    LEFT JOIN discount PERCNTAGE_DISCOUNT on PD.ID = PERCNTAGE_DISCOUNT.ID AND PERCNTAGE_DISCOUNT.TYPE = 'PERCENTAGE'
    LEFT JOIN biggestCategoryDiscount bcd on P.CATEGORY = bcd.CATEGORY_ID CROSS JOIN
    (
      select
        MAX(CASE WHEN d.TYPE = 'ABSOLUTE' THEN d.VALUE ELSE 0 END ) AS ABSOLUTE,
        MAX(CASE WHEN d.TYPE = 'PERCENTAGE' THEN d.VALUE ELSE 0 END) AS PERCENTAGE
      FROM discount d
        LEFT JOIN categoryDiscount C on d.ID = C.ID
        LEFT JOIN productDiscount P on d.ID = P.ID
      WHERE P.ID IS NULL AND C.ID IS NULL ) e
  GROUP BY P.ID);