# This file should hold all the configuration that does not depend on
# the environment in which the app is running

databaseSchema: dejavu

rest:
  basePath: /api

auth:
  secret: changeit
  rights:
    REGULAR:
      - GET /api/user/{id}
      - POST /api/user/{id}
    ADMIN:
      - GET /api/user/*
      - GET /api/user/
      - POST /api/user/*/ban
      - POST /api/image/upload

flyway:
  placeholders:
    schemaName: ${databaseSchema}
    # Configuration for DB table and column names
    tables:
      user:
        name: user
        columns:
          id: id
          email: email
          password: password
          firstName: firstName
          lastName: lastName
          type: type
          banned: banned
      product:
        name: product
        columns:
          id: id
          name: name
          description: description
          category: category
          price: price
          creationDate: creationDate
      category:
        name: category
        columns:
          id: id
          name: name
          iconName: iconName
          displayName: displayName
          parentCategory: parentCategory

