# This file should hold all the configuration that does not depend on
# the environment in which the app is running

databaseSchema: dejavu

rest:
  basePath: /api

auth:
  secret: changeit
  rights:
    REGULAR:
      - GET /api/user/{id}
      - POST /api/user/{id}
    ADMIN:
      - GET /api/user/*
      - GET /api/user/
      - POST /api/user/*/ban

flyway:
  placeholders:
    schemaName: ${databaseSchema}
    # Configuration for DB table and column names
    tables:
      user:
        name: user
        columns:
          id: id
          email: email
          password: password
          firstName: firstName
          lastName: lastName
          type: type
          banned: banned

