# This file should hold all the configuration that does not depend on
# the environment in which the app is running

databaseSchema: dejavu

logging:
  level:
    lt.dejavu.web.logging.RequestLoggingFilter: DEBUG
    lt.dejavu.payment.interceptor.LoggingRequestInterceptor: DEBUG

rest:
  basePath: /api
  auth: ${rest.basePath}/auth
  category: ${rest.basePath}/category
  health: ${rest.basePath}/health
  image: ${rest.basePath}/image
  payment: ${rest.basePath}/payment
  product: ${rest.basePath}/product
  user: ${rest.basePath}/user


auth:
  secret: changeit
  rights:
    REGULAR:
      - GET ${rest.user}/{id}
      - POST ${rest.user}/{id}
    ADMIN:
      - GET ${rest.user}/*
      - GET ${rest.user}/
      - POST ${rest.user}/*/ban
      - POST ${rest.image}/upload

flyway:
  placeholders:
    schemaName: ${databaseSchema}
    # Configuration for DB table and column names
    tables:
      user:
        name: user
        columns:
          id: id
          email: email
          password: password
          firstName: firstName
          lastName: lastName
          type: type
          banned: banned
      product:
        name: product
        columns:
          id: id
          name: name
          description: description
          category: category
          price: price
          creationDate: creationDate
      category:
        name: category
        columns:
          id: id
          name: name
          iconName: iconName
          displayName: displayName
          parentCategory: parentCategory

payment:
  paymentServiceAddress: http://mock-payment-processor.appspot.com
  credentials:
    username: technologines
    password: platformos
