rest:
  basePath: /api

spring:
  datasource:
    hibernate-dialect: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/dejavudb
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
