# This file should contain prod-specific configuration

spring:
  datasource:
    hibernate-dialect: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/dejavudb
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

flyway:
  placeholders:
    types:
      text: TEXT
      bool: BIT(1)

fileStorage:
  rootDirectoy: /path/to/files