databaseSchema: dejavu

rest:
  basePath: /api

auth:
  secret: changeit
  rights:
    REGULAR:
      - GET /api/user/{id}
      - POST /api/user/{id}
    ADMIN:
      - GET /api/user/*
      - GET /api/user/
      - POST /api/user/*/ban

spring:
  datasource:
    url: jdbc:h2:mem:dejavu_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hibernate-dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /dejavu_dev
      # h2 console available at http://localhost:8080/dejavu_dev

flyway:
  placeholders:
    schemaName: ${databaseSchema}
    # Configuration for DB table and column names
    tables:
      user:
        name: user
        columns:
          id: id
          email: email
          password: password
          firstName: firstName
          lastName: lastName
          type: type
          banned: banned
      product:
        name: product
        columns:
          id: id
          name: name
          description: description
          category: category
          price: price
          creationDate: creationDate
      category:
        name: category
        columns:
          id: id
          name: name
          iconName: iconName
          displayName: displayName
          parentCategory: parentCategory

