# This file should contain development-specific configuration

spring:
  datasource:
    hibernate-dialect: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:dejavu_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /dejavu_dev
      # h2 console available at http://localhost:8080/dejavu_dev

flyway:
  placeholders:
    types:
      text: VARCHAR(80000)
      bool: BIT

storage:
  basePath: @project.build.directory@\files\images
  # basePath resolves to djv-web/target/files/images