# This file should contain prod-specific configuration

spring:
  datasource:
    hibernate-dialect: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/dejavudb
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    debug:
      show-sql: false
      format-sql: false

flyway:
  placeholders:
    types:
      text: TEXT
      bool: BIT(1)
      uuid: BINARY(16)

storage:
  basePath: /path/to/files