# This file should contain development-specific configuration

debug: true

spring:
  datasource:
    hibernate-dialect: org.hibernate.dialect.H2Dialect
    url:  jdbc:h2:~/h2database/DJV-database2;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    debug:
      show-sql: true
      format-sql: true
  h2:
    console:
      enabled: true
      path: /dejavu_dev
      # h2 console available at http://localhost:8080/dejavu_dev

flyway:
  placeholders:
    types:
      text: VARCHAR(80000)
      bool: BIT

storage:
  basePath: @project.build.directory@\files\images
  # basePath resolves to djv-web/target/files/images