CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(255),
  lastName VARCHAR(255),
  userType VARCHAR(10) NOT NULL
);

CREATE TABLE userToken (
  userId INT PRIMARY KEY,
  accessToken UUID UNIQUE,

  FOREIGN KEY (userId) REFERENCES user(id)
);